package edu.utm.bd.domain;

import java.util.ArrayList;
import java.util.List;

public class ClienteExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public ClienteExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdClienteIsNull() {
			addCriterion("id_cliente is null");
			return (Criteria) this;
		}

		public Criteria andIdClienteIsNotNull() {
			addCriterion("id_cliente is not null");
			return (Criteria) this;
		}

		public Criteria andIdClienteEqualTo(Integer value) {
			addCriterion("id_cliente =", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteNotEqualTo(Integer value) {
			addCriterion("id_cliente <>", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteGreaterThan(Integer value) {
			addCriterion("id_cliente >", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_cliente >=", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteLessThan(Integer value) {
			addCriterion("id_cliente <", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteLessThanOrEqualTo(Integer value) {
			addCriterion("id_cliente <=", value, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteIn(List<Integer> values) {
			addCriterion("id_cliente in", values, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteNotIn(List<Integer> values) {
			addCriterion("id_cliente not in", values, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteBetween(Integer value1, Integer value2) {
			addCriterion("id_cliente between", value1, value2, "idCliente");
			return (Criteria) this;
		}

		public Criteria andIdClienteNotBetween(Integer value1, Integer value2) {
			addCriterion("id_cliente not between", value1, value2, "idCliente");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("nombre is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("nombre is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("nombre =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("nombre <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("nombre >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("nombre >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("nombre <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("nombre <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("nombre like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("nombre not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("nombre in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("nombre not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("nombre between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("nombre not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andDomicilioIsNull() {
			addCriterion("domicilio is null");
			return (Criteria) this;
		}

		public Criteria andDomicilioIsNotNull() {
			addCriterion("domicilio is not null");
			return (Criteria) this;
		}

		public Criteria andDomicilioEqualTo(String value) {
			addCriterion("domicilio =", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotEqualTo(String value) {
			addCriterion("domicilio <>", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioGreaterThan(String value) {
			addCriterion("domicilio >", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioGreaterThanOrEqualTo(String value) {
			addCriterion("domicilio >=", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioLessThan(String value) {
			addCriterion("domicilio <", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioLessThanOrEqualTo(String value) {
			addCriterion("domicilio <=", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioLike(String value) {
			addCriterion("domicilio like", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotLike(String value) {
			addCriterion("domicilio not like", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioIn(List<String> values) {
			addCriterion("domicilio in", values, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotIn(List<String> values) {
			addCriterion("domicilio not in", values, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioBetween(String value1, String value2) {
			addCriterion("domicilio between", value1, value2, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotBetween(String value1, String value2) {
			addCriterion("domicilio not between", value1, value2, "domicilio");
			return (Criteria) this;
		}

		public Criteria andRfcIsNull() {
			addCriterion("RFC is null");
			return (Criteria) this;
		}

		public Criteria andRfcIsNotNull() {
			addCriterion("RFC is not null");
			return (Criteria) this;
		}

		public Criteria andRfcEqualTo(String value) {
			addCriterion("RFC =", value, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcNotEqualTo(String value) {
			addCriterion("RFC <>", value, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcGreaterThan(String value) {
			addCriterion("RFC >", value, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcGreaterThanOrEqualTo(String value) {
			addCriterion("RFC >=", value, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcLessThan(String value) {
			addCriterion("RFC <", value, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcLessThanOrEqualTo(String value) {
			addCriterion("RFC <=", value, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcLike(String value) {
			addCriterion("RFC like", value, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcNotLike(String value) {
			addCriterion("RFC not like", value, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcIn(List<String> values) {
			addCriterion("RFC in", values, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcNotIn(List<String> values) {
			addCriterion("RFC not in", values, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcBetween(String value1, String value2) {
			addCriterion("RFC between", value1, value2, "rfc");
			return (Criteria) this;
		}

		public Criteria andRfcNotBetween(String value1, String value2) {
			addCriterion("RFC not between", value1, value2, "rfc");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andTelefonoIsNull() {
			addCriterion("telefono is null");
			return (Criteria) this;
		}

		public Criteria andTelefonoIsNotNull() {
			addCriterion("telefono is not null");
			return (Criteria) this;
		}

		public Criteria andTelefonoEqualTo(Integer value) {
			addCriterion("telefono =", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotEqualTo(Integer value) {
			addCriterion("telefono <>", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoGreaterThan(Integer value) {
			addCriterion("telefono >", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoGreaterThanOrEqualTo(Integer value) {
			addCriterion("telefono >=", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoLessThan(Integer value) {
			addCriterion("telefono <", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoLessThanOrEqualTo(Integer value) {
			addCriterion("telefono <=", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoIn(List<Integer> values) {
			addCriterion("telefono in", values, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotIn(List<Integer> values) {
			addCriterion("telefono not in", values, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoBetween(Integer value1, Integer value2) {
			addCriterion("telefono between", value1, value2, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotBetween(Integer value1, Integer value2) {
			addCriterion("telefono not between", value1, value2, "telefono");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cliente
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 14 17:38:50 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}