package edu.utm.bd.domain;

public class Cliente {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cliente.id_cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	private Integer idCliente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cliente.nombre
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cliente.domicilio
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	private String domicilio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cliente.RFC
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	private String rfc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cliente.email
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cliente.telefono
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	private String telefono;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cliente.id_cliente
	 * @return  the value of cliente.id_cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public Integer getIdCliente() {
		return idCliente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cliente.id_cliente
	 * @param idCliente  the value for cliente.id_cliente
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cliente.nombre
	 * @return  the value of cliente.nombre
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cliente.nombre
	 * @param nombre  the value for cliente.nombre
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cliente.domicilio
	 * @return  the value of cliente.domicilio
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public String getDomicilio() {
		return domicilio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cliente.domicilio
	 * @param domicilio  the value for cliente.domicilio
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cliente.RFC
	 * @return  the value of cliente.RFC
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public String getRfc() {
		return rfc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cliente.RFC
	 * @param rfc  the value for cliente.RFC
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cliente.email
	 * @return  the value of cliente.email
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cliente.email
	 * @param email  the value for cliente.email
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cliente.telefono
	 * @return  the value of cliente.telefono
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cliente.telefono
	 * @param telefono2  the value for cliente.telefono
	 * @mbggenerated  Wed Apr 25 18:12:03 CDT 2018
	 */
	public void setTelefono(String telefono2) {
		this.telefono = telefono2;
	}
}