package edu.utm.bd.domain;

import java.util.Date;

public class Factura {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factura.id_factura
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    private Integer idFactura;
    private Integer idVenta;    
    private Venta venta;    
    private Integer total;    
    private Integer importe;    
    private Factura folio;
    private Integer cantidad;
    private String descripcion;
    private Double precioVenta;
    private Integer idProducto;
    private Date fecha;
    private String nombre;
    private String domicilio;
    private String rfc;
    private String email;
    private Integer telefono;
    private Integer numVenta;
    
    public Factura (){
    	setVenta(new Venta());
    }
    
    public Venta getVenta() {
		return venta;
	}

	public void setVenta(Venta venta) {
		this.venta = venta;
	}

	private Cliente cliente;
	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	private Producto producto;
	public Producto getProducto() {
		return producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factura.id_factura
     *
     * @return the value of factura.id_factura
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public Integer getIdFactura() {
        return idFactura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factura.id_factura
     *
     * @param idFactura the value for factura.id_factura
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factura.id_venta
     *
     * @return the value of factura.id_venta
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public Integer getIdVenta() {
        return idVenta;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factura.id_venta
     *
     * @param idVenta the value for factura.id_venta
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }

	public Integer getImporte() {
		return importe;
	}

	public void setImporte(Integer importe) {
		this.importe = importe;
	}

	public Integer getTotal() {
		return total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public Factura getFolio() {
		return folio;
	}
	
	public void setFolio(Factura folio) {
		this.folio = folio;
	}

	public Integer getCantidad() {
		return cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getPrecioVenta() {
		return precioVenta;
	}

	public void setPrecioVenta(Double precioVenta) {
		this.precioVenta = precioVenta;
	}

	public Integer getIdProducto() {
		return idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDomicilio() {
		return domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getRfc() {
		return rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Integer getTelefono() {
		return telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public Integer getNumVenta() {
		return numVenta;
	}

	public void setNumVenta(Integer numVenta) {
		this.numVenta = numVenta;
	}
}