package edu.utm.bd.domain;

import java.util.Date;

public class Venta {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venta.id_venta
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    private Integer idVenta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venta.id_cliente
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    private Integer idCliente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venta.id_producto
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    private Integer idProducto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venta.fecha
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    private Date fecha;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venta.id_venta
     *
     * @return the value of venta.id_venta
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    private Integer numVenta;
    private Integer cantidad;
    private Producto producto;
    private Double ganancia;
    private String tipo;
    private String marca;
    private Double precioVenta;
    private String nombre;
    private String descripcion;
    private Double suma;
    
    public Integer getNumVenta() {
		return numVenta;
	}

	public void setNumVenta(Integer numVenta) {
		this.numVenta = numVenta;
	}

	public Integer getCantidad() {
		return cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getMarca() {
		return marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public Double getPrecioVenta() {
		return precioVenta;
	}

	public void setPrecioVenta(Double precioVenta) {
		this.precioVenta = precioVenta;
	}

	public Integer getIdVenta() {
        return idVenta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venta.id_venta
     *
     * @param idVenta the value for venta.id_venta
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venta.id_cliente
     *
     * @return the value of venta.id_cliente
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venta.id_cliente
     *
     * @param idCliente the value for venta.id_cliente
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venta.id_producto
     *
     * @return the value of venta.id_producto
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public Integer getIdProducto() {
        return idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venta.id_producto
     *
     * @param idProducto the value for venta.id_producto
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venta.fecha
     *
     * @return the value of venta.fecha
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venta.fecha
     *
     * @param fecha the value for venta.fecha
     *
     * @mbggenerated Wed Apr 25 18:12:03 CDT 2018
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

	public Producto getProducto() {
		return producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Double getGanancia() {
		return ganancia;
	}

	public void setGanancia(Double ganancia) {
		this.ganancia = ganancia;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getSuma() {
		return suma;
	}

	public void setSuma(Double suma) {
		this.suma = suma;
	}
}